package org.simulink.FtcSimulinkRuntime;

import org.firstinspires.ftc.teamcode.simulink.SimulinkRuntimeBridge;

/**
 * TeamCode-owned host for the JNI contract generated by the Simulink Android target.
 *
 * <p>The fully qualified class name and the two native method declarations are part of
 * the generated library ABI. This class intentionally is not an Android Activity. The
 * generated native runtime only retains the supplied Java object and calls the public
 * callback methods below.</p>
 */
public final class FtcSimulinkRuntime {
    private static final FtcSimulinkRuntime INSTANCE = new FtcSimulinkRuntime();
    private static final Object START_LOCK = new Object();

    private static final Throwable LIBRARY_LOAD_FAILURE;
    private static boolean startAttempted;
    private static Thread launcherThread;

    static {
        Throwable failure = null;
        try {
            System.loadLibrary("FtcSimulinkRuntime");
        } catch (Throwable throwable) {
            failure = throwable;
        }
        LIBRARY_LOAD_FAILURE = failure;

        if (failure != null) {
            SimulinkRuntimeBridge.recordNativeFailure(
                    "Unable to load libFtcSimulinkRuntime.so", failure);
        }
    }

    private FtcSimulinkRuntime() {
    }

    /**
     * Starts the generated scheduler once for the lifetime of the Robot Controller process.
     */
    public static boolean startOnce() {
        synchronized (START_LOCK) {
            if (LIBRARY_LOAD_FAILURE != null) {
                return false;
            }
            if (startAttempted) {
                return !SimulinkRuntimeBridge.hasTerminalNativeFault();
            }

            startAttempted = true;
            SimulinkRuntimeBridge.recordNativeStarted();
            launcherThread = new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        String[] argv = new String[]{"TeamCode", "FtcSimulinkRuntime"};
                        int exitCode = INSTANCE.naMain(argv, INSTANCE);
                        SimulinkRuntimeBridge.recordNativeLauncherReturn(exitCode);
                    } catch (Throwable throwable) {
                        SimulinkRuntimeBridge.recordNativeFailure(
                                "Simulink native launcher failed", throwable);
                    }
                }
            }, "FtcSimulinkRuntime-Launcher");
            launcherThread.setDaemon(true);
            launcherThread.start();
            return true;
        }
    }

    public static boolean isLibraryLoaded() {
        return LIBRARY_LOAD_FAILURE == null;
    }

    public static boolean wasStartAttempted() {
        synchronized (START_LOCK) {
            return startAttempted;
        }
    }

    public static boolean isLauncherThreadAlive() {
        synchronized (START_LOCK) {
            return launcherThread != null && launcherThread.isAlive();
        }
    }

    public float[] getModelInputs() {
        return SimulinkRuntimeBridge.getInputsForModel();
    }

    public void setModelOutputs(float[] modelOutputs) {
        SimulinkRuntimeBridge.publishOutputs(modelOutputs);
    }

    public void flashMessage(String message) {
        SimulinkRuntimeBridge.recordNativeMessage(message);
    }

    /**
     * The generated runtime calls this method when it terminates. It must never finish the
     * FTC Robot Controller activity; instead, it records a terminal fault and lets TeamCode
     * zero all actuator commands.
     */
    public void terminateApp() {
        SimulinkRuntimeBridge.recordNativeTermination();
    }

    private native int naMain(String[] argv, FtcSimulinkRuntime runtime);

    @SuppressWarnings("unused")
    private native void naOnAppStateChange(int state);
}
